rootLogger.level = WARN
rootLogger.appenderRef.stdout.ref = STDOUT

appender.stdout.type = Console
appender.stdout.name = STDOUT
appender.stdout.layout.type = PatternLayout
appender.stdout.layout.pattern = %d{HH:mm:ss} %-5p %c{1} - %m%n

logger.spark.name = org.apache.spark
logger.spark.level = WARN
logger.iceberg.name = org.apache.iceberg
logger.iceberg.level = INFO
